# Generated by Django 4.2.6 on 2023-10-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpucomp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='testtext',
            field=models.CharField(default='text', max_length=100),
            preserve_default=False,
        ),
    ]
