# Generated by Django 4.2.7 on 2023-11-17 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpucomp', '0002_cpu_testtext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='testnumber',
            new_name='cost',
        ),
    ]
