# Generated by Django 4.2.7 on 2023-11-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpucomp', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cart_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
