# Generated by Django 4.2.7 on 2023-11-17 11:42

import cpucomp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpucomp', '0005_userprofile_cart_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cart_data',
            field=models.JSONField(default=cpucomp.models.UserProfile.default_cart_data),
        ),
    ]
